## Tensorflow là gì?

Tensor flow là thư viện mã nguồn mở về học máy và học sâu được google phát hành mã nguồn miễn phí cho công đồng lập trình.  Let us understand the three models of the TensorFlow: data model, programming model, and execution model.

1. Import the TensorFlow Library with the following code:

import tensorflow as tf

2. Get a TensorFlow session. TensorFlow offers two kinds of sessions: Session() and InteractiveSession(). We will create an interactive session (phiên tương tác) with the following code:

tfs = tf.InteractiveSession()

Sự khác biết của Session() và InteractiveSession() đó là InteractiveSession() là mặc định nên sử dụng không cần phải bổ sung các yếu tố khác nữa.

3. Define a TensorFlow constant, hello:

hello = tf.constant("Hello TensorFlow !!")

4. Execute the constant in a TensorFlow session and print the output:

print(tfs.run(hello)



In [44]:
import tensorflow as tf

tfs = tf.InteractiveSession()

string = tf.constant("Hello TensorFlow !!")

print(tfs.run(string))



b'Hello TensorFlow !!'


## Tensors

Tensors là thành phần cơ bản trong Tensor flow. Tensor là một mảng nhiều chiều được xác định bởi rank,shape, type

+ Rank : là số chiều của tensors. 
+ Shape: Kích thước trong mỗi chiều
+ Type : kiểu dữ liệu 


## Constants

The constant valued tensors are created using the tf.constant() function that has the following signature:

tf.constant(value,dtype=None,shape=None,name='Const',verify_shape=False)

EX:

c1=tf.constant(5,name='x')
c2=tf.constant(6.0,name='y')
c3=tf.constant(7.0,tf.float32,name='z')


In [4]:
c1=tf.constant(5,name='x')
c2=tf.constant(6.0,name='y')
c3=tf.constant(7.0,tf.float32,name='z')

print(c1, tfs.run(c1))

Tensor("x:0", shape=(), dtype=int32) 5


## Operations

Trong tensor cũng cung cấp nhiều operater cho hai tensor cần cùng một loại dữ liệu



In [8]:
sub = tf.subtract(c2, c3)
add = tf.add(c2, c3)
print("Sub : ",tfs.run(sub))
print("Add : ", tfs.run(add))

Sub :  -1.0
Add :  13.0


## Placeholders

Việc này tương tự như khai báo một biến với một kiểu dữ liệu như trên các ngôn ngữ C/C++...

Cú pháp : 

tf.placeholder( dtype,shape=None,name=None)


In [9]:
p1 = tf.placeholder(tf.float32)
p2 = tf.placeholder(tf.float32)
print('p1 : ', p1)
print('p2 : ', p2)

op4 = p1 * p2
print('run(op4,{p1:2.0, p2:3.0}) : ',tfs.run(op4,{p1:2.0, p2:3.0}))


p1 :  Tensor("Placeholder:0", dtype=float32)
p2 :  Tensor("Placeholder_1:0", dtype=float32)
run(op4,{p1:2.0, p2:3.0}) :  6.0


We can create tensors from Python objects such as lists and NumPy arrays, using the tſ. convert_to_tensor () operation with the following signature:

tf. convert_to_tensor (value,dtype=None,name=None,preferred dtype=None)


In [19]:
import numpy as np
#  Create and print a 0-D Tensor:

tf_t = tf.convert_to_tensor(5.0, dtype = tf.float32)

print(tf_t, tfs.run(tf_t))

# Create and print a 1-D Tensor:

a = np.array([1,2,3,4])
tf_t = tf.convert_to_tensor(a, dtype = tf.int64)

print(tf_t, tfs.run(tf_t))

# access a elements of tensor 1-D is the same array 1-D or vector

print("tf_t [0] : ", tfs.run(tf_t[0]))

# Creat and print a 2-D Tensor or matrix 

a2 = np. array ( [ (1, 2, 3, 4, 5.99),(2, 3, 4, 5, 6.99),(3, 4, 5, 6, 7.99) ])
print ("a2 Shape : ", a2.shape)
tf_t= tf.convert_to_tensor(a2, dtype=tf.float64)
print(tf_t, tfs.run(tf_t))

Tensor("Const_12:0", shape=(), dtype=float32) 5.0
Tensor("Const_13:0", shape=(4,), dtype=int64) [1 2 3 4]
tf_t [0] :  1
a2 Shape :  (3, 5)
Tensor("Const_14:0", shape=(3, 5), dtype=float64) [[1.   2.   3.   4.   5.99]
 [2.   3.   4.   5.   6.99]
 [3.   4.   5.   6.   7.99]]


In [20]:
a=tf.zeros((100,))
print(tfs.run(a))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


##  Populating tensor elements with the same values

tf.zeros( shape,dtype=tf.float32, name=None)

Creates a tensor of the provided shape, with all elements set to zero

tf.zero_like(tensor, dtype = tf.float32, name = None) 

Create a tensor of the provided shape from a tensor other, and all elenments set to zero

Besides, we can init a tensor with all elements set to one. It is the same zero but change zeros by one





## Populating tensor elements with sequences

tf.lin_space( start, stop, num, name)

Creat 1-D tensor from a sequence of num numbers within the range [start, stop]. The tensor has the same data type as the
start argument.

For example, a = tf.lin_space(1,100,10) generates a tensor with
values [1,12,23,34,45,56,67,78,89,100].



In [25]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())


[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 6513698884167604651
]


In [55]:
tf.reset_default_graph ()
# Define model parameters
w = tf.Variable( [ .3 ] , tf.float32)

b = tf.Variable ([-.3] , tf.float32)
# Define model input and output
x = tf.placeholder(tf.float32)
y = w*x + b
config = tf.ConfigProto()
config.log_device_placement=True
with tf.Session(config=config) as tfs:
    # initialize and print the variable y
    tf.global_variables_initializer().run()
    print('output ', tfs.run(y, {x : [1, 2, 3, 4] }))

output  [0.         0.3        0.6        0.90000004]


In [53]:
import tensorflow as tf


x = tf.constant([35, 40, 45], name='x')
y = tf.Variable(x + 5, name='y')


model = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(model)
    print(session.run(y))

[40 45 50]


In [51]:
import tensorflow as tf


x = tf.Variable(0, name='x')

model = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(model)
    for i in range(5):
        x = x + 1
        print(session.run(x))

1
2
3
4
5


In [68]:
tf.reset_default_graph()
with tf.device('/device:CPU:0') :
# Define model parameters
    w = tf.get_variable(name='w', initializer= [.3], dtype= tf.float32 )
    b = tf.get_variable (name='b', initializer=[-.3], dtype=tf.float32)
#Define model input and output
    x = tf.placeholder (name='x', dtype=tf.float32) 
    y = w * x + b
config = tf.ConfigProto ()
config.log_device_placement=True
with tf.Session(config=config) as tfs:
# initialize and print the variable y
    tfs.run(tf.global_variables_initializer() )
    print ('output ', tfs.run(y, {x : [1, 2, 3, 4]}))


output  [0.         0.3        0.6        0.90000004]


In [69]:
tf.contrib.learn.KMeansClustering
tf.contrib.learn.DNNClassifier
tf.contrib.learn.DNNRegressor
tf.contrib.learn.DNNLinearCombinedRegressor
tf.contrib.learn.DNNLinearCombinedClassifier
tf.contrib.learn.LinearClassifier
tf.contrib.learn.LinearRegressor
tf.contrib.learn.LogisticRegressor


<function tensorflow.contrib.learn.python.learn.estimators.logistic_regressor.LogisticRegressor(model_fn, thresholds=None, model_dir=None, config=None, feature_engineering_fn=None)>